CREATE TABLE public.user (
  id BIGSERIAL PRIMARY KEY,
  username CHARACTER VARYING(32) NOT NULL,
  guid CHARACTER VARYING(256) NOT NULL DEFAULT '',
  email CHARACTER VARYING(128) NOT NULL,
  password CHARACTER VARYING(128) NOT NULL,
  salt CHARACTER VARYING(128) NOT NULL DEFAULT '',
  created_at TIMESTAMP WITH TIME ZONE
)