CREATE TABLE public.session (
  id BIGSERIAL PRIMARY KEY,
  session_id CHARACTER VARYING(256) NOT NULL UNIQUE,
  user_id BIGINT NULL,
  session_start TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  session_update TIMESTAMP WITH TIME ZONE NULL,
  session_active SMALLINT NOT NULL
)